apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql-sset
spec:
  serviceName: psql-svc
  replicas: 1
  selector:
    matchLabels:
      app: psql-sset
  template:
    metadata:
      labels:
        app: psql-sset
    spec:
      containers:
        - name: psql-sset
          image: docker.io/hilbertshotel/psql
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: psql-secret
                key: psql-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: psql-secret
                key: psql-password
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc
---
apiVersion: v1
kind: Service
metadata:
  name: psql-svc
spec:
  selector:
    app: psql-sset
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
