apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-deployment
  labels:
    app: psql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql-deployment
  template:
    metadata:
      labels:
        app: psql-deployment
    spec:
      containers:
      - name: psql-deployment
        image: hilbertshotel/cmstp-psql:latest
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: psql-secret
                key: psql-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: psql-secret
                key: psql-password 